name: "Test-Containerize-Deploy"

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
      - main


  
jobs:
  publish:
    runs-on: ubuntu-ubuntu-latest
    strategy:
      matrix:
        node: [16.x, 18.x, 20.x]

    name: Node ${{ matrix.node }} sample
    steps:
      - name: 'Checkout'
      - uses: actions/checkout@v4

      - name: Setup nodejs
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
    
      - name: Build
      - run: npm run build:prod